/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shnayder_heartratemonitor_HeartRateMonitorPreview */

#ifndef _Included_com_shnayder_heartratemonitor_HeartRateMonitorPreview
#define _Included_com_shnayder_heartratemonitor_HeartRateMonitorPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shnayder_heartratemonitor_HeartRateMonitorPreview
 * Method:    hrmNativeStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_shnayder_heartratemonitor_HeartRateMonitorPreview_hrmNativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_shnayder_heartratemonitor_HeartRateMonitorPreview
 * Method:    hrmNativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shnayder_heartratemonitor_HeartRateMonitorPreview_hrmNativeStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
